### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by winspool** [alehaa/git-tools#2]
There is no licence.

Can you please add a license file?
I suggest MIT, as this is used also in many of your other projects.

-- 
Regards ... Detlef

**Comment by alehaa** [comment]
Indeed. This repository is ancient and just an upload of some local scripts, so I never thought about that …

Any specific requirements? Otherwise I would make a new release with MIT license added.

**Comment by winspool** [comment]
> Indeed. This repository is ancient and just an upload of some local scripts, so I never thought about that …
> 
> Any specific requirements? Otherwise I would make a new release with MIT license added.

No requirements, do whatever you like.
